### PR TITLE
`operator` is reserved keyword in Haxe 4.0.0-preview5

### LINKED ISSUE #9: Compatibility problem with Haxe 4.0.0-preview.5
Using haxelib git on master 54945d2384ed5edcc7a12822e7f14d9e6d56793d:

```
/usr/local/lib/haxe/lib/hamcrest/git/src/org/hamcrest/core/ShortcutCombination.hx:15: characters 9-17 : Unexpected operator
```

[`operator` is reserved keyword in Haxe 4.0.0-preview.5](https://haxe.org/download/version/4.0.0-preview.5/), therefore sadly we have to rename this.

### PR DESCRIPTION
**Pull request by kaikoga**
Fixes #9.

ping @mikestead

### CODE REVIEW

**Comment by SlavaRa** [comment]
@mikestead

**Comment by SlavaRa** [comment]
Bump

**Comment by SlavaRa** [comment]
Bump

**Comment by mikestead** [comment]
Thanks @kaikoga released under `v3.0.0`

**Pull request merged**
